<?xml version="1.0"?>
<robot name="box_template" xmlns:xacro="http://ros.org/wiki/xacro">	

	<include filename="$(find raw_description)/urdf/materials.urdf.xacro" />

	<xacro:macro name="box_template" params="name length width height color">
		<link name="${name}_link">
			<inertial>
				<origin xyz="${length / 2} ${width / 2} ${height / 2}" rpy="0 0 0" />
				<mass value="10.0" />
			    <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" />
			</inertial>

			<visual>
				<origin xyz="${length / 2} ${width / 2} ${height / 2}" rpy="0 0 0" />
				<geometry>
					<box size="${length} ${width} ${height}" />
				</geometry>
			</visual>

			<collision>
				<origin xyz="${length / 2} ${width / 2} ${height / 2}" rpy="0 0 0" />
				<geometry>
			   		<box size="${length} ${width} ${height}" />
				</geometry>
			</collision >
		</link>
		
		<gazebo reference="${name}_link">
			<material>${color}</material>
			<selfCollide>true</selfCollide>
		</gazebo>
		
	</xacro:macro> 
</robot>	
